# Generated by Django 3.1 on 2020-08-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.BinaryField(verbose_name=bytes),
        ),
    ]
